### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [IGNF/cartes-ign-app#86]
### Le besoin que vous rencontrez

ref: https://f-droid.org/docs/Inclusion_Policy/

Are Google proprietary libs needed? https://github.com/IGNF/cartes-ign-app/blob/v3.0.3/android/build.gradle#L11

**Comment by azarz** [comment]
Currently, Google Play Services are needed to use Geolocation on Android devices, because of the Capacitor Geolocation plugin: 
https://capacitorjs.com/docs/apis/geolocation#variables

According to this post, it is possible to access Geolocation without Google Services: https://github.com/ionic-team/capacitor/discussions/3528

I can make changes on the source code to support geolocation on Android devices without Google Services, but the dependency will still appear in the build.gradle. I don't know if this will still be an issue for F-Droid.

Unanswered post on the capacitor repo asking for support of other microg implementations : https://github.com/ionic-team/capacitor/discussions/5865

**Comment by licaon-kter** [comment]
you can separate the two with gradle flavors, F-Droid build recipe will clean the unneeded deps, yes

**Comment by azarz** [comment]
Is it mandatory to use flavors, or can I test the availability of google services and fallback to the non-google implementation?

**Comment by licaon-kter** [comment]
the flavors was to separate the used/loaded dependencies

eg. at build time, the code used to build the app needs to be fully FOSS.

> can I test the availability of google services and fallback to the non-google implementation?

you can't fall back to "proprietary libs" since those can't be in the FOSS app to begin with

as mentioned in the linked issues, you might try to use microG replacement libs, and yes, then, since those are FOSS, can try to detect what you want and use what you need.

**Comment by azarz** [comment]
Can you provide an example of gradle flavor configuration that builds the app without a given dependency for F-Droid, and does not change anything for the Play Store?
I think I can use a try/catch clause to fallback on a non-google services implementation, because it would also be beneficial for Play Store users to be able to use the Geolocation on the app without using Google services.

**Comment by licaon-kter** [comment]
> it would also be beneficial for Play Store users to be able to use the Geolocation on the app without using Google services.

true, but this is separate from whatever is needed for F-Droid (aka for the app to be built fully FOSS)

> Can you provide an example of gradle flavor configuration that builds the app without a given dependency for F-Droid, and does not change anything for the Play Store?

I'm no dev, so maybe https://codeberg.org/iNPUTmice/Conversations/src/tag/2.16.4/build.gradle#L162-L168

and then separate the per flavor parts likehttps://codeberg.org/iNPUTmice/Conversations/src/tag/2.16.4/src/playstore

and https://codeberg.org/iNPUTmice/Conversations/src/tag/2.16.4/src/free

**Comment by azarz** [comment]
I have created a pull request here: https://github.com/IGNF/cartes-ign-app/pull/87 it adds the `fdroid` flavor that is supposed to build without Google services. Could you review it?

Should I add a github actions pipeline to automate deployment on Fdroid? If so, can you provide me with examples?

**Comment by azarz** [comment]
@licaon-kter Here is the fdroid-compatible v3.1.1.
https://github.com/IGNF/cartes-ign-app/releases/tag/v3.1.1-foss

This is the only -foss specific release as the changes made in the PR will be included in all subsequent releases.

**Comment by licaon-kter** [comment]
report: https://beta.pithus.org/report/6c30591c7869f83138136c1831c85a2472dfd0c68baa17f5cb693ca19a61ce5a

**Comment by licaon-kter** [comment]
@azarz why does the app connect to https://ignf.github.io/ ?

**Comment by azarz** [comment]
https://github.com/IGNF/cartes-ign-app/blob/6983a7cc5963e01a60c3a7d8fddce64da2b9d87c/src/js/status-popups.js#L27

https://ignf.github.io/cartes-ign-services-uptime/edito.json
At this location is located a json that we use to display a "Message of the Day" at app launch when needed (e.g. giving info about a platform maintenance that will make the app unusable at a given time). This is from a private repo.

**Comment by licaon-kter** [comment]
Done: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15316 :tada: 

FYI https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by azarz** [comment]
https://f-droid.org/fr/packages/fr.ign.geoportail/

**Comment by azarz** [comment]
@licaon-kter There is an issue on the F-Droid build that I overlooked: at build time, the app needs a .env file with some secrets in it in order for some layers to work.
Is it possible to add secrets in the F-Droid recipe?

**Comment by licaon-kter** [comment]
F-Droid builds from free or open-source code.

Everything that is needed for the app must be either in your repo or in the recipe.

We can't have secrets: https://f-droid.org/docs/Inclusion_Policy/
> F-Droid does not sign up for any API keys. Even if provided by a third party, we include them in both, binary and sourcecode releases.

Secrets can always be extracted from the APK anyway.

What we can do is to obfuscate it a bit so it's not in the clear, but it's not hidden either, eg. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/oss.krtirtho.spotube.yml#L892-893

**Comment by azarz** [comment]
Thanks for the info! I'll check with my colleagues if we can do the obfuscation thing.

**Comment by azarz** [comment]
@licaon-kter I've made a MR to add the obfuscated secrets to the build: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15622/
