### ISSUE TITLE
layer Topo25 not displayed

### ISSUE THREAD

**Issue by dhardy92** [IGNF/cartes-ign-app#93]
### Description

When choosing Topo 25 only ayer in layer selection and validating, Map does not show tiles.

### Comportement attendu

See topo 25 tiles as map background

### Comment reproduire l'anomalie

Click on layer selectionicon, un select default tiles and select "topo 25".
Validate.

**Comment by Yaya-Cout** [comment]
I have the same problem on the F-Droid version but I think (from what I have read in #86) that it's due to F-Droid not using API keys.

**Comment by philibeur** [comment]
Hello, in my side, the f-droid and the google play version have this issue.

**Comment by azarz** [comment]
@dhardy92 @Yaya-Cout @philibeur 
The 3.1.7 version of the app released on August 31 should resolve the problem.

**Comment by philibeur** [comment]
Thank you for the fix.
