### ISSUE TITLE
Localisation inaccessible mais autorisée

### ISSUE THREAD

**Issue by Chaman-veteran** [IGNF/cartes-ign-app#94]
### Description

Parfois (de manière aléatoire ? En tout cas je n'ai pas encore compris le pattern), l'app ne peut pas me localiser et me mets le popup "L'accès à la localisation de votre appareil n'est pas autorisé. Pour pouvoir utiliser le positionnement sur la carte, veuillez modifier les paramètres de l'application." alors qu'elle a bien les accès :/

### Comportement attendu

Si la localisation tombe en échec, une autre erreur devrait être affichée, sinon la localisation devrait fonctionner normalement.

### Comment reproduire l'anomalie

Malheureusement je n'arrive pas à reproduire le bug, il apparaît de temps en temps et quand j'ouvre à nouveau l'app plus tard dans la journée ça remarche...

### Complément de contexte

J'ai un Pixel 6A (Android 14) et la version 3.1.3 (téléchargée via F-droid).

**Comment by azarz** [comment]
Bonjour,

Merci pour votre remontée !
Je vais creuser le sujet, je pense que cela est dû aux spécificités de comportement de l'application utilisées pour sa version F-Droid.

**Comment by Chaman-veteran** [comment]
Pas de soucis :)

Si besoin je veux bien essayer d'avoir des logs (adb ?) mais je ne sais pas si c'est utile ni comment faire x)

**Comment by azarz** [comment]
J'ai déjà une [piste de résolution](https://github.com/IGNF/cartes-ign-app/tree/fix-location-authorisation-fdroid), mais si elle s'avère inefficace je serai preneur des logs, oui !

**Comment by azarz** [comment]
J'ai trouvé la solution, elle sera disponible dans la prochaine mise à jour ! :)
https://github.com/IGNF/cartes-ign-app/pull/99

**Comment by azarz** [comment]
Bonjour @Chaman-veteran ,
Est-ce que vous rencontrez toujours le souci sur les dernières versions de l'application publiées sur F-Droid ?

**Comment by Chaman-veteran** [comment]
Bonjour @azarz,
Merci pour le fix, je n'ai effectivement pas rencontré ce problème avec la dernière version sur F-Droid :)
