### ISSUE TITLE
Cartes IGN n'affiche que le logo ou un écran noir.

### ISSUE THREAD

**Issue by Rpnpif** [IGNF/cartes-ign-app#95]
### Description

Cartes IGN ne se lance pas correctement.

### Comportement attendu

Cartes IGN devrait se lancer normalement comme sur la version précédente.

### Comment reproduire l'anomalie

Lancer Cartes IGN issu soit de Google store ou de F-Droid (même symptôme).
L'écran de lancement s'affiche (le logo de Cartes IGN au milieu). Rien d'autres ne se passe.
Si je change d'application puis si je reviens sur Cartes IGN, un écran noir s'affiche.

### Complément de contexte

Android 8.0 sur Huawei. Cartes IGN version 3.1.3
Adb logcat affiche :
07-15 15:26:16.804  1161  1189 W ActivityManager: setHasOverlayUi called on unknown pid: 17854
07-15 15:26:17.161  1161  1161 W ActivityManager: Sending non-protected broadcast huawei.intent.action.hideHiResIcon from system uid 1000 pkg null
07-15 15:26:17.169  1161  1161 W ActivityManager: Sending non-protected broadcast huawei.intent.action.hideHiResIcon from system uid 1000 pkg null
07-15 15:26:17.291  1161  1161 W ActivityManager: Sending non-protected broadcast huawei.intent.action.hideHiResIcon from system uid 1000 pkg null
07-15 15:26:17.318  1161  1161 W ActivityManager: Sending non-protected broadcast huawei.intent.action.hideHiResIcon from system uid 1000 pkg null
07-15 15:26:26.343  1161  1942 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.ign.geoportail/.MainActivity bnds=[540,84][804,370]} from uid 10064
07-15 15:26:26.349  1161  1942 I ActivityManager: ActivityRecord info: ActivityInfo{308d711 fr.ign.geoportail.MainActivity}
07-15 15:26:26.363  1161  1942 W ActivityManager: Unable to start service Intent { act=com.huawei.launcher.action.LAUNCHER_APP_STARTUP pkg=com.huawei.trustspace (has extras) } U=0: not found
07-15 15:26:26.381  1161  1942 I ActivityManager: Start proc 18034:fr.ign.geoportail/u0a97 for activity fr.ign.geoportail/.MainActivity
07-15 15:26:26.757  1161  9563 I ActivityManager: Start proc 18060:com.google.android.webview:sandboxed_process0/u0i13 for webview_service fr.ign.geoportail/org.chromium.content.app.SandboxedProcessService0
07-15 15:26:36.363  1161  1180 W ActivityManager: Launch timeout has expired, giving up wake lock!

**Comment by azarz** [comment]
Bonjour,

Merci pour votre remontée détaillée !

Si je comprends bien, le bug est apparu avec une nouvelle de l'application ? Si c'est bien le cas, pouvez-vous via F-Droid installer les versions successives (3.1.1 puis 3.1.2 puis 3.1.3) pour m'aider à déterminer quand le bug est apparu ?

**Comment by Rpnpif** [comment]
F-droid ne comporte pas de version autre que 3.1.3.. Je suppose que vous parlez de Android Webview plutôt que Huawei Webview. Mon Android est 8.0 donc ancien. J'ai enlevé les mises à jour d'Android Webview et je suis retombé à la version d'usine 70.0 du fait d'un manque de place en mémoire interne. C'est peut-être depuis ce temps que le bogue est apparu. Dès que j'ai un moment, je vais revenir à une version récente de Webview (par exemple la 126) au moins pour déterminer si c'est la cause du bogue.

Je vous tiens au courant.

**Comment by Rpnpif** [comment]
Je viens d'installer la version 126 d'Android System Webview (après avoir fait du ménage) et **Cartes IGN fonctionne bien** (sous Android 8.0).
Mais cela ne me donne pas la version minimale d'Android System Webview nécessaire.

Merci pour les pistes que vous m'avez donné.

**Comment by azarz** [comment]
Merci beaucoup pour votre retour ! Je vais investiguer de mon côté pour déterminer la version exacte minimal d'AndroidWebview.
